### ISSUE TITLE
Parser.parseNum() no support `Long` type number?

### ISSUE THREAD

**Issue by LiShuMing** [typelevel/jawn#72]
@non  when I use jawn lib, some error happens below:

> [info]   java.lang.NumberFormatException: For input string: "1493016373269"
[info]   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[info]   at java.lang.Integer.parseInt(Integer.java:583)
[info]   at java.lang.Integer.parseInt(Integer.java:615)
[info]   at jawn.support.json4s.Parser$$anon$1.jint(Parser.scala:15)
[info]   at jawn.support.json4s.Parser$$anon$1.jint(Parser.scala:10)
[info]   at jawn.Parser.parseNum(Parser.scala:188)
[info]   at jawn.Parser.rparse(Parser.scala:392)
[info]   at jawn.AsyncParser.churn(AsyncParser.scala:213)
[info]   at jawn.AsyncParser.finish(AsyncParser.scala:98)
[info]   at jawnstreamz.package$$anonfun$parseJson$1$$anonfun$apply$2.apply(package.scala:31)

How to fix it ?

**Comment by LiShuMing** [comment]
oh , I found a solution in support folder, just chage false to true, solve problems above.

thx, any more.

> package jawn
package support.json4s

import scala.collection.mutable
import org.json4s.JsonAST._

* object Parser extends Parser(true, true) *
